package ui;

import data.GestorEntidades;
import javax.swing.JOptionPane;
import model.ColaboradorExterno;
import model.GuiaTuristico;
import model.Registrable;
import model.Vehiculo;

public class Main extends javax.swing.JFrame {

    private GestorEntidades gestor = new GestorEntidades();

    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        panelTitulo = new javax.swing.JLabel();
        panelSaludo = new javax.swing.JLabel();
        panelVer = new javax.swing.JPanel();
        verTitulo = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();
        btnVer = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaPanel = new javax.swing.JTextArea();
        panelRegistro1 = new javax.swing.JPanel();
        regTitulo1 = new javax.swing.JLabel();
        regNombre = new javax.swing.JLabel();
        regRutCodigo = new javax.swing.JLabel();
        regPregunta2 = new javax.swing.JLabel();
        regUnico = new javax.swing.JLabel();
        regTelDisp = new javax.swing.JLabel();
        cmbSeleccion = new javax.swing.JComboBox<>();
        txtNombre = new javax.swing.JTextField();
        txtRutCodigo = new javax.swing.JTextField();
        txtUnico = new javax.swing.JTextField();
        txtTelDisp = new javax.swing.JTextField();
        btnRegistro = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelPrincipal.setBackground(new java.awt.Color(0, 102, 51));

        panelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        panelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        panelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelTitulo.setText("LLANQUIHUE TOUR");
        panelTitulo.setToolTipText("");
        panelTitulo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        panelSaludo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        panelSaludo.setForeground(new java.awt.Color(255, 255, 255));
        panelSaludo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelSaludo.setText("Bienvenido al sitema de gestión");

        panelVer.setBackground(new java.awt.Color(0, 102, 102));

        verTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        verTitulo.setForeground(new java.awt.Color(255, 255, 255));
        verTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        verTitulo.setText("Ver Registro");

        btnLimpiar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnVer.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnVer.setText("VER REGISTRO");
        btnVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerActionPerformed(evt);
            }
        });

        txtaPanel.setColumns(20);
        txtaPanel.setRows(5);
        jScrollPane1.setViewportView(txtaPanel);

        javax.swing.GroupLayout panelVerLayout = new javax.swing.GroupLayout(panelVer);
        panelVer.setLayout(panelVerLayout);
        panelVerLayout.setHorizontalGroup(
            panelVerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVerLayout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(verTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelVerLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(panelVerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(panelVerLayout.createSequentialGroup()
                        .addComponent(btnVer, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19))
        );
        panelVerLayout.setVerticalGroup(
            panelVerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(verTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(panelVerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVer, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelRegistro1.setBackground(new java.awt.Color(0, 102, 102));

        regTitulo1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        regTitulo1.setForeground(new java.awt.Color(255, 255, 255));
        regTitulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        regTitulo1.setText("Registrar Nuevo");

        regNombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        regNombre.setForeground(new java.awt.Color(255, 255, 255));
        regNombre.setText("Nombre:");

        regRutCodigo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        regRutCodigo.setForeground(new java.awt.Color(255, 255, 255));
        regRutCodigo.setText("Rut:");

        regPregunta2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        regPregunta2.setForeground(new java.awt.Color(255, 255, 255));
        regPregunta2.setText("¿Que desea Registrar?");

        regUnico.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        regUnico.setForeground(new java.awt.Color(255, 255, 255));
        regUnico.setText("Empresa:");

        regTelDisp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        regTelDisp.setForeground(new java.awt.Color(255, 255, 255));
        regTelDisp.setText("Telefono:");

        cmbSeleccion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbSeleccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Colaborador", "Guia Turistico", "Vehiculo" }));
        cmbSeleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSeleccionActionPerformed(evt);
            }
        });

        txtNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtRutCodigo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtUnico.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtTelDisp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnRegistro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRegistro.setText("REGISTRAR");
        btnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRegistro1Layout = new javax.swing.GroupLayout(panelRegistro1);
        panelRegistro1.setLayout(panelRegistro1Layout);
        panelRegistro1Layout.setHorizontalGroup(
            panelRegistro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegistro1Layout.createSequentialGroup()
                .addGroup(panelRegistro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRegistro1Layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(regTitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 109, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRegistro1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(panelRegistro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(regPregunta2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(regNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(regRutCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(regTelDisp, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(regUnico, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelRegistro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbSeleccion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNombre)
                            .addComponent(txtRutCodigo)
                            .addComponent(txtUnico)
                            .addComponent(txtTelDisp)
                            .addComponent(btnRegistro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE))))
                .addGap(36, 36, 36))
        );
        panelRegistro1Layout.setVerticalGroup(
            panelRegistro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegistro1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(regTitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addGroup(panelRegistro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regPregunta2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbSeleccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(panelRegistro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(panelRegistro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regRutCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRutCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(panelRegistro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regTelDisp, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelDisp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(panelRegistro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regUnico, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUnico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(btnRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        btnSalir.setBackground(new java.awt.Color(255, 51, 51));
        btnSalir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(panelSaludo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE))
                        .addGap(35, 35, 35)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                        .addComponent(panelRegistro1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(panelVer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(panelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelSaludo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)))
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelVer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelRegistro1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(panelPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbSeleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSeleccionActionPerformed

        String seleccion = cmbSeleccion.getSelectedItem().toString();

        if (seleccion.equals("Colaborador")) {
            regNombre.setText("Nombre:");
            regRutCodigo.setText("Rut:");
            regTelDisp.setText("Telefono:");
            regUnico.setText("Empresa:");
        } else if (seleccion.equals("Guia Turistico")) {
            regNombre.setText("Nombre:");
            regRutCodigo.setText("Rut:");
            regTelDisp.setText("Telefono:");
            regUnico.setText("Certificado");
        } else if (seleccion.equals("Vehiculo")) {
            regNombre.setText("Nombre:");
            regRutCodigo.setText("Codigo:");
            regTelDisp.setText("Disponible:");
            regUnico.setText("Patente:");
        }
    }//GEN-LAST:event_cmbSeleccionActionPerformed

    private void btnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroActionPerformed

        String seleccion = cmbSeleccion.getSelectedItem().toString();
        Registrable nuevoObjeto = null;
        int telefono = 0;

        if (seleccion.equals("Colaborador") || seleccion.equals("Guia Turistico")) {
            try {
                telefono = Integer.parseInt(txtTelDisp.getText());
            } catch (NumberFormatException e) {
                javax.swing.JOptionPane.showMessageDialog(this, "El teléfono debe ser numérico.");
                return;
            }
        }

        if (seleccion.equals("Colaborador")) {
            nuevoObjeto = new ColaboradorExterno(txtNombre.getText(), txtRutCodigo.getText(), telefono, txtUnico.getText());

        } else if (seleccion.equals("Vehiculo")) {
            nuevoObjeto = new Vehiculo(txtNombre.getText(), txtRutCodigo.getText(), txtTelDisp.getText(), txtUnico.getText());

        } else if (seleccion.equals("Guia Turistico")) {

            nuevoObjeto = new GuiaTuristico(txtNombre.getText(), txtRutCodigo.getText(), telefono, txtUnico.getText());
        }

        if (nuevoObjeto != null) {
            gestor.agregarEntidad(nuevoObjeto);
            JOptionPane.showMessageDialog(this, nuevoObjeto.registrar(), "Registro Exitoso", JOptionPane.INFORMATION_MESSAGE);

            txtNombre.setText("");
            txtRutCodigo.setText("");
            txtTelDisp.setText("");
            txtUnico.setText("");

        }

    }//GEN-LAST:event_btnRegistroActionPerformed

    private void btnVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerActionPerformed

        txtaPanel.setText(gestor.mostrarResumen());

    }//GEN-LAST:event_btnVerActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed

        txtaPanel.setText("");

    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        int respuesta = JOptionPane.showConfirmDialog(
                this,
                "Desea salir del sistema?",
                "Confirmar salida",
                JOptionPane.YES_NO_OPTION
        );

        if (respuesta == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar1;
    private javax.swing.JButton btnGuardar2;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRegistro;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnVer;
    private javax.swing.JButton btnVolverMenu1;
    private javax.swing.JButton btnVolverMenu2;
    private javax.swing.JComboBox<String> cmbSeleccion;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelGuia1;
    private javax.swing.JPanel panelGuia2;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelRegistro1;
    private javax.swing.JLabel panelSaludo;
    private javax.swing.JLabel panelTitulo;
    private javax.swing.JPanel panelVer;
    private javax.swing.JLabel regNombre;
    private javax.swing.JLabel regPregunta2;
    private javax.swing.JLabel regRutCodigo;
    private javax.swing.JLabel regTelDisp;
    private javax.swing.JLabel regTitulo1;
    private javax.swing.JLabel regUnico;
    private javax.swing.JLabel registroCap1;
    private javax.swing.JLabel registroCap2;
    private javax.swing.JLabel registroNombre1;
    private javax.swing.JLabel registroNombre2;
    private javax.swing.JLabel registroRut1;
    private javax.swing.JLabel registroRut2;
    private javax.swing.JLabel registroTelefono1;
    private javax.swing.JLabel registroTelefono2;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtRegistroCap1;
    private javax.swing.JTextField txtRegistroCap2;
    private javax.swing.JTextField txtRegistroNombre1;
    private javax.swing.JTextField txtRegistroNombre2;
    private javax.swing.JTextField txtRegistroRut1;
    private javax.swing.JTextField txtRegistroRut2;
    private javax.swing.JTextField txtRegistroTel1;
    private javax.swing.JTextField txtRegistroTel2;
    private javax.swing.JTextField txtRutCodigo;
    private javax.swing.JTextField txtTelDisp;
    private javax.swing.JTextField txtUnico;
    private javax.swing.JTextArea txtaPanel;
    private javax.swing.JLabel verTitulo;
    // End of variables declaration//GEN-END:variables
}
