package ui;

import data.GestorArchivos;
import data.GestorPersonas;
import data.GestorRecursos;
import data.GestorReservas;
import data.GestorServicios;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.Cliente;
import model.ColaboradorExterno;
import model.Embarcacion;
import model.Excursion;
import model.GuiaTuristico;
import model.PaseoLacustre;
import model.Persona;
import model.RecursoAgencia;
import model.Registrable;
import model.ReservaTuristica;
import model.ServicioTuristico;
import model.TourGastronomico;
import model.Vehiculo;

public class Main extends javax.swing.JFrame {

    private GestorArchivos motor;
    private GestorPersonas gp;
    private GestorRecursos gr;
    private GestorServicios gs;
    private GestorReservas gres;
    private ArrayList<String> listaTemporalRuts = new ArrayList<>();

    public Main() {
        initComponents();

        this.motor = new GestorArchivos();
        this.gp = new GestorPersonas(motor);
        this.gr = new GestorRecursos(motor);
        this.gs = new GestorServicios(motor);
        this.gres = new GestorReservas(motor);

        cmbPersonas.addActionListener(evt -> {
            String seleccion = (String) cmbPersonas.getSelectedItem();
            if ("Guia turistico".equals(seleccion)) {
                personaVariable.setText("Capacitacion:");
            } else if ("Colaborador externo".equals(seleccion)) {
                personaVariable.setText("Empresa:");
            } else {
                personaVariable.setText("Edad:");
            }
        });

        cmbRecursos.addActionListener(evt -> {
            String seleccion = (String) cmbRecursos.getSelectedItem();
            if ("Vehiculo".equals(seleccion)) {
                recursoVariable.setText("Kilometraje:");
            } else if ("Embarcacion".equals(seleccion)) {
                recursoVariable.setText("Capacidad:");
            }
        });

        cmbServicio.addActionListener(evt -> {
            String seleccion = (String) cmbServicio.getSelectedItem();
            if ("Excursion".equals(seleccion)) {
                servicioVariable.setText("Kilometros:");
            } else if ("Paseo Lacustre".equals(seleccion)) {
                servicioVariable.setText("Puerto embarque:");
            } else if ("Tour gastronomico".equals(seleccion)) {
                servicioVariable.setText("No. Paradas:");
            }
        });

        reservaServicio.setVisible(false);
        reservaGuia.setVisible(false);
        reservaRecurso.setVisible(false);
        reservaRut.setVisible(false);
        cmbReservaServicio.setVisible(false);
        cmbReservaGuia.setVisible(false);
        cmbReservaRecurso.setVisible(false);
        txtReservaCodigo.setVisible(false);
        btnRerservaCancelar.setVisible(false);
        btnReservaAgregar.setVisible(false);
        btnReservaGuardar.setVisible(false);

        cmbReservaMes.addActionListener(evt -> {
            if (cmbReservaMes.getSelectedItem() != null) {
                int mesSeleccionado = cmbReservaMes.getSelectedIndex() + 1;

                reservaServicio.setVisible(true);
                reservaGuia.setVisible(true);
                reservaRecurso.setVisible(true);
                reservaRut.setVisible(true);
                cmbReservaServicio.setVisible(true);
                cmbReservaGuia.setVisible(true);
                cmbReservaRecurso.setVisible(true);
                txtReservaCodigo.setVisible(true);
                btnRerservaCancelar.setVisible(true);
                btnReservaAgregar.setVisible(true);
                btnReservaGuardar.setVisible(true);
                btnReservaVer.setVisible(true);

                cmbReservaServicio.removeAllItems();
                for (ServicioTuristico s : gs.obtenerServiciosDisponibles(mesSeleccionado, gres)) {
                    cmbReservaServicio.addItem(s.getNombre());
                }

                cmbReservaGuia.removeAllItems();
                for (GuiaTuristico g : gp.obtenerGuiasDisponibles(mesSeleccionado, gres)) {
                    cmbReservaGuia.addItem(g.getNombre());
                }

                cmbReservaRecurso.removeAllItems();
                for (RecursoAgencia r : gr.obtenerRecursosDisponibles(mesSeleccionado, gres)) {
                    cmbReservaRecurso.addItem(r.getNombre());
                }
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        tabPricipal = new javax.swing.JTabbedPane();
        tabPersonas = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbPersonas = new javax.swing.JComboBox<>();
        personaNombre = new javax.swing.JLabel();
        txtPersonaNombre = new javax.swing.JTextField();
        txtPersonaRut = new javax.swing.JTextField();
        personaRut = new javax.swing.JLabel();
        txtPersonaTelefono = new javax.swing.JTextField();
        personaTelefono = new javax.swing.JLabel();
        txtPersonaVariable = new javax.swing.JTextField();
        personaVariable = new javax.swing.JLabel();
        btnBorrarPersona = new javax.swing.JButton();
        btnVerPersona = new javax.swing.JButton();
        btnRegistrarPersona = new javax.swing.JButton();
        tabRecursos = new javax.swing.JPanel();
        recursoTexto = new javax.swing.JLabel();
        recursoTexto2 = new javax.swing.JLabel();
        recursoNombre = new javax.swing.JLabel();
        txtRecursoNombre = new javax.swing.JTextField();
        recursoCodigo = new javax.swing.JLabel();
        txtRecursoCodigo = new javax.swing.JTextField();
        recursoDisponible = new javax.swing.JLabel();
        recursoVariable = new javax.swing.JLabel();
        txtRecursoVariable = new javax.swing.JTextField();
        cmbRecursos = new javax.swing.JComboBox<>();
        btnRegistrarRecurso = new javax.swing.JButton();
        btnBorrarRecurso = new javax.swing.JButton();
        btnVerRecurso = new javax.swing.JButton();
        cmbDisponible = new javax.swing.JComboBox<>();
        tabServicios = new javax.swing.JPanel();
        servicioTexto = new javax.swing.JLabel();
        servicioTexto2 = new javax.swing.JLabel();
        servicioNombre = new javax.swing.JLabel();
        txtServicioNombre = new javax.swing.JTextField();
        servicioCodigo = new javax.swing.JLabel();
        txtServicioCodigo = new javax.swing.JTextField();
        servicioCantidad = new javax.swing.JLabel();
        txtServicioCantidad = new javax.swing.JTextField();
        servicioVariable = new javax.swing.JLabel();
        txtServicioVariable = new javax.swing.JTextField();
        cmbServicio = new javax.swing.JComboBox<>();
        btnRegistrarServicio = new javax.swing.JButton();
        btnBorrarServicio = new javax.swing.JButton();
        btnVerServicio = new javax.swing.JButton();
        tabReservas = new javax.swing.JPanel();
        reservaTexto = new javax.swing.JLabel();
        reservaTexto2 = new javax.swing.JLabel();
        reservaServicio = new javax.swing.JLabel();
        reservaGuia = new javax.swing.JLabel();
        reservaRecurso = new javax.swing.JLabel();
        reservaRut = new javax.swing.JLabel();
        cmbReservaMes = new javax.swing.JComboBox<>();
        btnRerservaCancelar = new javax.swing.JButton();
        btnReservaAgregar = new javax.swing.JButton();
        cmbReservaGuia = new javax.swing.JComboBox<>();
        cmbReservaServicio = new javax.swing.JComboBox<>();
        cmbReservaRecurso = new javax.swing.JComboBox<>();
        btnReservaGuardar = new javax.swing.JButton();
        btnReservaVer = new javax.swing.JButton();
        txtReservaCodigo = new javax.swing.JTextField();
        reservaCodigo = new javax.swing.JLabel();
        btnReservaEliminar = new javax.swing.JButton();
        txtReservaEliminar = new javax.swing.JTextField();
        btnSalir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtaPanelBlanco = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelPrincipal.setBackground(new java.awt.Color(0, 51, 0));

        tabPricipal.setVerifyInputWhenFocusTarget(false);

        tabPersonas.setBackground(new java.awt.Color(0, 51, 51));
        tabPersonas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REGISTRAR PERSONAS");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("¿Que deseas registrar?");

        cmbPersonas.setBackground(new java.awt.Color(255, 255, 204));
        cmbPersonas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cliente", "Colaborador externo", "Guia turistico" }));

        personaNombre.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        personaNombre.setForeground(new java.awt.Color(255, 255, 255));
        personaNombre.setText("Nombre:");

        txtPersonaNombre.setBackground(new java.awt.Color(255, 255, 204));

        txtPersonaRut.setBackground(new java.awt.Color(255, 255, 204));

        personaRut.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        personaRut.setForeground(new java.awt.Color(255, 255, 255));
        personaRut.setText("Rut:");

        txtPersonaTelefono.setBackground(new java.awt.Color(255, 255, 204));

        personaTelefono.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        personaTelefono.setForeground(new java.awt.Color(255, 255, 255));
        personaTelefono.setText("Telefono");

        txtPersonaVariable.setBackground(new java.awt.Color(255, 255, 204));

        personaVariable.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        personaVariable.setForeground(new java.awt.Color(255, 255, 255));
        personaVariable.setText("Edad:");

        btnBorrarPersona.setBackground(new java.awt.Color(255, 255, 204));
        btnBorrarPersona.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBorrarPersona.setText("BORRAR PERSONA");
        btnBorrarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarPersonaActionPerformed(evt);
            }
        });

        btnVerPersona.setBackground(new java.awt.Color(255, 255, 204));
        btnVerPersona.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVerPersona.setText("VER REGISTRO");
        btnVerPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerPersonaActionPerformed(evt);
            }
        });

        btnRegistrarPersona.setBackground(new java.awt.Color(255, 255, 204));
        btnRegistrarPersona.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRegistrarPersona.setText("REGISTRAR");
        btnRegistrarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarPersonaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tabPersonasLayout = new javax.swing.GroupLayout(tabPersonas);
        tabPersonas.setLayout(tabPersonasLayout);
        tabPersonasLayout.setHorizontalGroup(
            tabPersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabPersonasLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(tabPersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabPersonasLayout.createSequentialGroup()
                        .addGroup(tabPersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(tabPersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(personaRut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtPersonaRut, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(tabPersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(personaNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtPersonaNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))
                            .addGroup(tabPersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(personaTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtPersonaTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(tabPersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(personaVariable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtPersonaVariable, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tabPersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbPersonas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRegistrarPersona, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBorrarPersona, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnVerPersona, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(527, 527, 527))
                    .addGroup(tabPersonasLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        tabPersonasLayout.setVerticalGroup(
            tabPersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabPersonasLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(15, 15, 15)
                .addGroup(tabPersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(personaNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPersonaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(tabPersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(personaRut)
                    .addComponent(btnRegistrarPersona))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPersonaRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(tabPersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(personaTelefono)
                    .addComponent(btnBorrarPersona))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPersonaTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(tabPersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(personaVariable)
                    .addComponent(btnVerPersona))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPersonaVariable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        tabPricipal.addTab("PERSONAS", tabPersonas);

        tabRecursos.setBackground(new java.awt.Color(0, 102, 102));

        recursoTexto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        recursoTexto.setForeground(new java.awt.Color(255, 255, 255));
        recursoTexto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        recursoTexto.setText("REGISTRAR RECURSOS");

        recursoTexto2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        recursoTexto2.setForeground(new java.awt.Color(255, 255, 255));
        recursoTexto2.setText("¿Que deseas registrar?");

        recursoNombre.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        recursoNombre.setForeground(new java.awt.Color(255, 255, 255));
        recursoNombre.setText("Nombre:");

        txtRecursoNombre.setBackground(new java.awt.Color(255, 255, 204));

        recursoCodigo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        recursoCodigo.setForeground(new java.awt.Color(255, 255, 255));
        recursoCodigo.setText("Codigo:");

        txtRecursoCodigo.setBackground(new java.awt.Color(255, 255, 204));

        recursoDisponible.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        recursoDisponible.setForeground(new java.awt.Color(255, 255, 255));
        recursoDisponible.setText("Disponibilidad:");

        recursoVariable.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        recursoVariable.setForeground(new java.awt.Color(255, 255, 255));
        recursoVariable.setText("Kilometraje:");

        txtRecursoVariable.setBackground(new java.awt.Color(255, 255, 204));

        cmbRecursos.setBackground(new java.awt.Color(255, 255, 204));
        cmbRecursos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Embarcacion", "Vehiculo" }));

        btnRegistrarRecurso.setBackground(new java.awt.Color(255, 255, 204));
        btnRegistrarRecurso.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRegistrarRecurso.setText("REGISTRAR");
        btnRegistrarRecurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarRecursoActionPerformed(evt);
            }
        });

        btnBorrarRecurso.setBackground(new java.awt.Color(255, 255, 204));
        btnBorrarRecurso.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBorrarRecurso.setText("BORRAR RECURSO");
        btnBorrarRecurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarRecursoActionPerformed(evt);
            }
        });

        btnVerRecurso.setBackground(new java.awt.Color(255, 255, 204));
        btnVerRecurso.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVerRecurso.setText("VER REGISTRO");
        btnVerRecurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerRecursoActionPerformed(evt);
            }
        });

        cmbDisponible.setBackground(new java.awt.Color(255, 255, 204));
        cmbDisponible.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Disponible", "No disponible" }));

        javax.swing.GroupLayout tabRecursosLayout = new javax.swing.GroupLayout(tabRecursos);
        tabRecursos.setLayout(tabRecursosLayout);
        tabRecursosLayout.setHorizontalGroup(
            tabRecursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabRecursosLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(tabRecursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabRecursosLayout.createSequentialGroup()
                        .addGroup(tabRecursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(recursoTexto2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(tabRecursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(recursoCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtRecursoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(tabRecursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(recursoNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtRecursoNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))
                            .addComponent(recursoDisponible, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(tabRecursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(recursoVariable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtRecursoVariable, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tabRecursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbRecursos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRegistrarRecurso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBorrarRecurso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnVerRecurso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(527, 527, 527))
                    .addGroup(tabRecursosLayout.createSequentialGroup()
                        .addGroup(tabRecursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(recursoTexto)
                            .addComponent(cmbDisponible, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        tabRecursosLayout.setVerticalGroup(
            tabRecursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabRecursosLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(recursoTexto)
                .addGap(15, 15, 15)
                .addGroup(tabRecursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(recursoTexto2)
                    .addComponent(cmbRecursos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(recursoNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtRecursoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(tabRecursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(recursoCodigo)
                    .addComponent(btnRegistrarRecurso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtRecursoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(tabRecursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(recursoDisponible)
                    .addComponent(btnBorrarRecurso))
                .addGap(12, 12, 12)
                .addComponent(cmbDisponible, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(tabRecursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(recursoVariable)
                    .addComponent(btnVerRecurso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtRecursoVariable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        tabPricipal.addTab("RECURSOS", tabRecursos);

        tabServicios.setBackground(new java.awt.Color(0, 153, 153));

        servicioTexto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        servicioTexto.setForeground(new java.awt.Color(255, 255, 255));
        servicioTexto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        servicioTexto.setText("REGISTRAR SERVICIOS");

        servicioTexto2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        servicioTexto2.setForeground(new java.awt.Color(255, 255, 255));
        servicioTexto2.setText("¿Que deseas registrar?");

        servicioNombre.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        servicioNombre.setForeground(new java.awt.Color(255, 255, 255));
        servicioNombre.setText("Nombre:");

        txtServicioNombre.setBackground(new java.awt.Color(255, 255, 204));

        servicioCodigo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        servicioCodigo.setForeground(new java.awt.Color(255, 255, 255));
        servicioCodigo.setText("Codigo:");

        txtServicioCodigo.setBackground(new java.awt.Color(255, 255, 204));

        servicioCantidad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        servicioCantidad.setForeground(new java.awt.Color(255, 255, 255));
        servicioCantidad.setText("Cantidad turistas:");

        txtServicioCantidad.setBackground(new java.awt.Color(255, 255, 204));

        servicioVariable.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        servicioVariable.setForeground(new java.awt.Color(255, 255, 255));
        servicioVariable.setText("Puerto embarque:");

        txtServicioVariable.setBackground(new java.awt.Color(255, 255, 204));

        cmbServicio.setBackground(new java.awt.Color(255, 255, 204));
        cmbServicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Excursion", "Paseo Lacustre", "Tour gastronomico" }));

        btnRegistrarServicio.setBackground(new java.awt.Color(255, 255, 204));
        btnRegistrarServicio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRegistrarServicio.setText("REGISTRAR");
        btnRegistrarServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarServicioActionPerformed(evt);
            }
        });

        btnBorrarServicio.setBackground(new java.awt.Color(255, 255, 204));
        btnBorrarServicio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBorrarServicio.setText("BORRAR SERVICIO");
        btnBorrarServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarServicioActionPerformed(evt);
            }
        });

        btnVerServicio.setBackground(new java.awt.Color(255, 255, 204));
        btnVerServicio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVerServicio.setText("VER REGISTRO");
        btnVerServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerServicioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tabServiciosLayout = new javax.swing.GroupLayout(tabServicios);
        tabServicios.setLayout(tabServiciosLayout);
        tabServiciosLayout.setHorizontalGroup(
            tabServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabServiciosLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(tabServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabServiciosLayout.createSequentialGroup()
                        .addGroup(tabServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(servicioTexto2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(tabServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(servicioCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtServicioCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(tabServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(servicioNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtServicioNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))
                            .addGroup(tabServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(servicioCantidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtServicioCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(tabServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(servicioVariable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtServicioVariable, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tabServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbServicio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRegistrarServicio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBorrarServicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnVerServicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(527, 527, 527))
                    .addGroup(tabServiciosLayout.createSequentialGroup()
                        .addComponent(servicioTexto)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        tabServiciosLayout.setVerticalGroup(
            tabServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabServiciosLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(servicioTexto)
                .addGap(15, 15, 15)
                .addGroup(tabServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(servicioTexto2)
                    .addComponent(cmbServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(servicioNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtServicioNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(tabServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(servicioCodigo)
                    .addComponent(btnRegistrarServicio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtServicioCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(tabServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(servicioCantidad)
                    .addComponent(btnBorrarServicio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtServicioCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(tabServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(servicioVariable)
                    .addComponent(btnVerServicio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtServicioVariable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        tabPricipal.addTab("SERVICIOS", tabServicios);

        tabReservas.setBackground(new java.awt.Color(0, 204, 102));

        reservaTexto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        reservaTexto.setForeground(new java.awt.Color(255, 255, 255));
        reservaTexto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        reservaTexto.setText("CREAR RESERVA TURISTICA");

        reservaTexto2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        reservaTexto2.setForeground(new java.awt.Color(255, 255, 255));
        reservaTexto2.setText("¿Para qué mes la desea?");

        reservaServicio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        reservaServicio.setForeground(new java.awt.Color(255, 255, 255));
        reservaServicio.setText("Seleccione un Servicio:");

        reservaGuia.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        reservaGuia.setForeground(new java.awt.Color(255, 255, 255));
        reservaGuia.setText("Seleccione un guia:");

        reservaRecurso.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        reservaRecurso.setForeground(new java.awt.Color(255, 255, 255));
        reservaRecurso.setText("Seleccione un vehiculo:");

        reservaRut.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        reservaRut.setForeground(new java.awt.Color(255, 255, 255));
        reservaRut.setText("Escriba rut de cliente(s):");

        cmbReservaMes.setBackground(new java.awt.Color(255, 255, 204));
        cmbReservaMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));

        btnRerservaCancelar.setBackground(new java.awt.Color(255, 255, 204));
        btnRerservaCancelar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRerservaCancelar.setText("CANCELAR PROCESO");
        btnRerservaCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRerservaCancelarActionPerformed(evt);
            }
        });

        btnReservaAgregar.setBackground(new java.awt.Color(255, 255, 204));
        btnReservaAgregar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnReservaAgregar.setText("AGREGAR CLIENTE");
        btnReservaAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservaAgregarActionPerformed(evt);
            }
        });

        cmbReservaGuia.setBackground(new java.awt.Color(255, 255, 204));

        cmbReservaServicio.setBackground(new java.awt.Color(255, 255, 204));

        cmbReservaRecurso.setBackground(new java.awt.Color(255, 255, 204));
        cmbReservaRecurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        btnReservaGuardar.setBackground(new java.awt.Color(255, 255, 204));
        btnReservaGuardar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnReservaGuardar.setText("GUARDAR RESERVA");
        btnReservaGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservaGuardarActionPerformed(evt);
            }
        });

        btnReservaVer.setBackground(new java.awt.Color(255, 255, 204));
        btnReservaVer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnReservaVer.setText("VER RESERVAS");
        btnReservaVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservaVerActionPerformed(evt);
            }
        });

        txtReservaCodigo.setBackground(new java.awt.Color(255, 255, 204));

        reservaCodigo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        reservaCodigo.setForeground(new java.awt.Color(255, 255, 255));
        reservaCodigo.setText("Codigo de reserva a eliminar:");

        btnReservaEliminar.setBackground(new java.awt.Color(255, 255, 204));
        btnReservaEliminar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnReservaEliminar.setText("ELIMINAR RESERVA");
        btnReservaEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservaEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tabReservasLayout = new javax.swing.GroupLayout(tabReservas);
        tabReservas.setLayout(tabReservasLayout);
        tabReservasLayout.setHorizontalGroup(
            tabReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabReservasLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(tabReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabReservasLayout.createSequentialGroup()
                        .addComponent(reservaTexto)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(tabReservasLayout.createSequentialGroup()
                        .addGroup(tabReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(reservaTexto2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reservaGuia, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reservaServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reservaRecurso, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(tabReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(cmbReservaGuia, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(reservaRut, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cmbReservaServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbReservaRecurso, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtReservaCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tabReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnReservaEliminar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnReservaGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, tabReservasLayout.createSequentialGroup()
                                .addComponent(cmbReservaMes, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(btnRerservaCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnReservaVer, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(reservaCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnReservaAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtReservaEliminar))
                        .addGap(527, 527, 527))))
        );
        tabReservasLayout.setVerticalGroup(
            tabReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabReservasLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(reservaTexto)
                .addGap(15, 15, 15)
                .addGroup(tabReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reservaTexto2)
                    .addComponent(cmbReservaMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(tabReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reservaServicio)
                    .addComponent(btnReservaGuardar))
                .addGap(17, 17, 17)
                .addGroup(tabReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbReservaServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRerservaCancelar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tabReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(reservaGuia)
                    .addComponent(btnReservaVer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabReservasLayout.createSequentialGroup()
                        .addComponent(cmbReservaGuia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabReservasLayout.createSequentialGroup()
                        .addComponent(reservaCodigo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(tabReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(reservaRecurso)
                    .addComponent(txtReservaEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tabReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbReservaRecurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReservaEliminar))
                .addGap(35, 35, 35)
                .addComponent(reservaRut)
                .addGap(18, 18, 18)
                .addGroup(tabReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReservaAgregar)
                    .addComponent(txtReservaCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        tabPricipal.addTab("RESERVAS", tabReservas);

        btnSalir.setBackground(new java.awt.Color(204, 0, 0));
        btnSalir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("LLANQUIHUE TOUR");

        txtaPanelBlanco.setColumns(20);
        txtaPanelBlanco.setRows(5);
        jScrollPane2.setViewportView(txtaPanelBlanco);

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tabPricipal, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(tabPricipal, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarPersonaActionPerformed

        String rut = txtPersonaRut.getText();
        String nombre = txtPersonaNombre.getText();
        String telefono = txtPersonaTelefono.getText();
        String tipo = (String) cmbPersonas.getSelectedItem();
        String variable = txtPersonaVariable.getText();

        // 1. Validaciones comunes
        if (!util.Validador.rutValido(rut)) { //
            javax.swing.JOptionPane.showMessageDialog(this, "RUT inválido.");
            return;
        }
        if (!util.Validador.textoValido(nombre)) { //
            javax.swing.JOptionPane.showMessageDialog(this, "Nombre inválido.");
            return;
        }
        if (!util.Validador.telefonoValido(telefono)) { //
            javax.swing.JOptionPane.showMessageDialog(this, "Teléfono inválido (9 dígitos).");
            return;
        }

        if ("Cliente".equals(tipo)) {
            if (!util.Validador.numeroPositivoValido(variable)) {
                javax.swing.JOptionPane.showMessageDialog(this, "La edad debe ser un número entero positivo.");
                return;
            }
        } else {
            if (!util.Validador.textoValido(variable)) {
                javax.swing.JOptionPane.showMessageDialog(this, "El campo " + personaVariable.getText() + " no puede estar vacío.");
                return;
            }
        }

        int telefonoInt = Integer.parseInt(telefono.trim());
        Persona nuevaPersona = null;

        if (tipo.equalsIgnoreCase("Cliente")) {
            int edad = Integer.parseInt(txtPersonaVariable.getText());
            nuevaPersona = new Cliente(rut, nombre, telefonoInt, edad);

        } else if (tipo.equalsIgnoreCase("Guia turistico")) {
            String capacitacion = txtPersonaVariable.getText();
            nuevaPersona = new GuiaTuristico(rut, nombre, telefonoInt, capacitacion);

        } else if (tipo.equalsIgnoreCase("Colaborador externo")) {
            String empresa = txtPersonaVariable.getText();
            nuevaPersona = new ColaboradorExterno(rut, nombre, telefonoInt, empresa);
        }

        if (nuevaPersona != null) {
            gp.agregarPersona(nuevaPersona);
            javax.swing.JOptionPane.showMessageDialog(this, nuevaPersona.registrar());
        }

        txtPersonaRut.setText("");
        txtPersonaNombre.setText("");
        txtPersonaTelefono.setText("");
        txtPersonaVariable.setText("");
        cmbPersonas.setSelectedIndex(0);

    }//GEN-LAST:event_btnRegistrarPersonaActionPerformed

    private void btnBorrarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarPersonaActionPerformed

        String rutABorrar = txtPersonaRut.getText().trim();

        if (!util.Validador.rutValido(rutABorrar)) {
            javax.swing.JOptionPane.showMessageDialog(this, "El RUT ingresado no tiene un formato válido (XXXXXXXX-X).");
            return;
        }

        boolean eliminado = gp.eliminarPersona(rutABorrar);

        if (eliminado) {
            javax.swing.JOptionPane.showMessageDialog(this, "Persona con RUT " + rutABorrar + " eliminada correctamente.");

            txtPersonaRut.setText("");
            txtPersonaNombre.setText("");
            txtPersonaTelefono.setText("");
            txtPersonaVariable.setText("");
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "No se encontró ninguna persona con ese RUT en el sistema.");
        }

        txtPersonaRut.setText("");

    }//GEN-LAST:event_btnBorrarPersonaActionPerformed

    private void btnVerPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerPersonaActionPerformed

        String reporte = gp.generarReportePersonas();

        if (reporte.isEmpty()) {
            txtaPanelBlanco.setText("No hay registros de personas actualmente.");
        } else {
            txtaPanelBlanco.setText(reporte);
        }

    }//GEN-LAST:event_btnVerPersonaActionPerformed

    private void btnRegistrarRecursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarRecursoActionPerformed

        String codigo = txtRecursoCodigo.getText();
        String nombre = txtRecursoNombre.getText();
        String tipo = (String) cmbRecursos.getSelectedItem();
        String variable = txtRecursoVariable.getText();
        boolean disponible = cmbDisponible.getSelectedItem().equals("Disponible");

        if (!util.Validador.textoValido(codigo)) {
            javax.swing.JOptionPane.showMessageDialog(this, "ID inválido.");
            return;
        }
        if (!util.Validador.textoValido(nombre)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Marca inválida.");
            return;
        }
        if (!util.Validador.numeroPositivoValido(variable)) {
            javax.swing.JOptionPane.showMessageDialog(this, "El valor de " + recursoVariable.getText() + " debe ser un número entero positivo.");
            return;
        }

        int valorInt = Integer.parseInt(variable.trim());

        RecursoAgencia nuevoRecurso = null;

        if (tipo.equalsIgnoreCase("Vehiculo")) {
            nuevoRecurso = new Vehiculo(codigo, nombre, disponible, valorInt);
        } else if (tipo.equalsIgnoreCase("Embarcacion")) {
            nuevoRecurso = new Embarcacion(codigo, nombre, disponible, valorInt);
        }

        if (nuevoRecurso != null) {
            gr.agregarRecurso(nuevoRecurso);
            javax.swing.JOptionPane.showMessageDialog(this, nuevoRecurso.registrar());
        }

        txtRecursoCodigo.setText("");
        txtRecursoNombre.setText("");
        txtRecursoVariable.setText("");
        cmbRecursos.setSelectedIndex(0);
        cmbDisponible.setSelectedIndex(0);

    }//GEN-LAST:event_btnRegistrarRecursoActionPerformed

    private void btnBorrarRecursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarRecursoActionPerformed

        String codigoABorrar = txtRecursoCodigo.getText().trim();

        if (!util.Validador.textoValido(codigoABorrar)) {
            javax.swing.JOptionPane.showMessageDialog(this, "El código ingresado no es válido.");
            return;
        }

        boolean eliminado = gr.eliminarRecurso(codigoABorrar);

        if (eliminado) {
            javax.swing.JOptionPane.showMessageDialog(this, "Recurso con código " + codigoABorrar + " eliminado correctamente.");

            txtRecursoCodigo.setText("");
            txtRecursoNombre.setText("");
            txtRecursoVariable.setText("");
            cmbDisponible.setSelectedIndex(0);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "No se encontró ningún recurso con ese código en el sistema.");
        }

        txtRecursoCodigo.setText("");

    }//GEN-LAST:event_btnBorrarRecursoActionPerformed

    private void btnVerRecursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerRecursoActionPerformed

        String reporte = gr.generarReporteRecursos();

        if (reporte.isEmpty()) {
            txtaPanelBlanco.setText("No hay registros de recursos actualmente.");
        } else {
            txtaPanelBlanco.setText(reporte);
        }
    }//GEN-LAST:event_btnVerRecursoActionPerformed

    private void btnRegistrarServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarServicioActionPerformed

        String codigo = txtServicioCodigo.getText();
        String nombre = txtServicioNombre.getText();
        String cantidadStr = txtServicioCantidad.getText();
        String tipo = (String) cmbServicio.getSelectedItem();
        String variable = txtServicioVariable.getText();

        if (!util.Validador.textoValido(codigo)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Código inválido.");
            return;
        }
        if (!util.Validador.textoValido(nombre)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Nombre inválido.");
            return;
        }
        if (!util.Validador.numeroPositivoValido(cantidadStr)) {
            javax.swing.JOptionPane.showMessageDialog(this, "La cantidad de turistas debe ser un número entero positivo.");
            return;
        }

        int cantidad = Integer.parseInt(cantidadStr.trim());

        ServicioTuristico nuevoServicio = null;

        if ("Paseo Lacustre".equals(tipo)) {
            if (!util.Validador.textoValido(variable)) {
                javax.swing.JOptionPane.showMessageDialog(this, "El campo " + servicioVariable.getText() + " es obligatorio.");
                return;
            }
            nuevoServicio = new PaseoLacustre(codigo, nombre, cantidad, variable);

        } else {
            if (!util.Validador.numeroPositivoValido(variable)) {
                javax.swing.JOptionPane.showMessageDialog(this, "El campo " + servicioVariable.getText() + " debe ser un número entero positivo.");
                return;
            }
            int valorVariable = Integer.parseInt(variable.trim());

            if ("Excursion".equals(tipo)) {
                nuevoServicio = new Excursion(codigo, nombre, cantidad, valorVariable);
            } else if ("Tour gastronomico".equals(tipo)) {
                nuevoServicio = new TourGastronomico(codigo, nombre, cantidad, valorVariable);
            }
        }

        if (nuevoServicio != null) {
            gs.agregarServicio(nuevoServicio);
            javax.swing.JOptionPane.showMessageDialog(this, nuevoServicio.registrar());
        }

        txtServicioCodigo.setText("");
        txtServicioNombre.setText("");
        txtServicioCantidad.setText("");
        txtServicioVariable.setText("");
        cmbServicio.setSelectedIndex(0);

    }//GEN-LAST:event_btnRegistrarServicioActionPerformed

    private void btnBorrarServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarServicioActionPerformed

        String codigoABorrar = txtServicioCodigo.getText().trim();

        if (!util.Validador.textoValido(codigoABorrar)) {
            javax.swing.JOptionPane.showMessageDialog(this, "El código ingresado no tiene un formato válido.");
            return;
        }

        boolean eliminado = gs.eliminarServicio(codigoABorrar);

        if (eliminado) {
            javax.swing.JOptionPane.showMessageDialog(this, "Servicio con código " + codigoABorrar + " eliminado correctamente.");

            txtServicioCodigo.setText("");
            txtServicioNombre.setText("");
            txtServicioCantidad.setText("");
            txtServicioVariable.setText("");
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "No se encontró ningún servicio con ese código en el sistema.");
        }

        txtServicioCodigo.setText("");

    }//GEN-LAST:event_btnBorrarServicioActionPerformed

    private void btnVerServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerServicioActionPerformed

        String reporte = gs.generarReporteServicios();

        if (reporte.isEmpty()) {
            txtaPanelBlanco.setText("No hay registros de servicios actualmente.");
        } else {
            txtaPanelBlanco.setText(reporte);
        }
    }//GEN-LAST:event_btnVerServicioActionPerformed

    private void btnReservaGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservaGuardarActionPerformed

        if (cmbReservaServicio.getSelectedItem() == null || cmbReservaGuia.getSelectedItem() == null || cmbReservaRecurso.getSelectedItem() == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: Debe seleccionar una opción en todos los campos.");
            return;
        }

        String servicioNombre = (String) cmbReservaServicio.getSelectedItem();
        ServicioTuristico servicio = gs.buscarServicioPorNombre(servicioNombre);

        if (servicio == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: El servicio seleccionado no es válido.");
            return;
        }

        if (listaTemporalRuts.size() != servicio.getCantidad()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: La cantidad de clientes ("
                    + listaTemporalRuts.size() + ") no coincide con la capacidad del servicio ("
                    + servicio.getCantidad() + ").");
            return;
        }

        int mes = cmbReservaMes.getSelectedIndex() + 1;
        String codigoReserva = "RES" + servicio.getCodigo() + mes;

        String nombreGuia = (String) cmbReservaGuia.getSelectedItem();
        String nombreRecurso = (String) cmbReservaRecurso.getSelectedItem();

        String rutGuia = gp.obtenerRutGuiaPorNombre(nombreGuia);
        String codigoRecurso = gr.obtenerCodigoRecursoPorNombre(nombreRecurso);

        ReservaTuristica nuevaReserva = new ReservaTuristica(codigoReserva, mes, rutGuia, codigoRecurso, servicio.getCodigo(), listaTemporalRuts);
        gres.registrarReserva(nuevaReserva, true);

        listaTemporalRuts.clear();
        javax.swing.JOptionPane.showMessageDialog(this, "Reserva guardada con éxito: " + codigoReserva);

        txtReservaCodigo.setText("");
        cmbReservaServicio.setSelectedIndex(0);
        cmbReservaGuia.setSelectedIndex(0);
        cmbReservaRecurso.setSelectedIndex(0);

        txtReservaCodigo.setVisible(false);
        btnReservaAgregar.setVisible(false);
        cmbReservaServicio.setVisible(false);
        cmbReservaGuia.setVisible(false);
        cmbReservaRecurso.setVisible(false);
        btnReservaGuardar.setVisible(false);
        btnReservaVer.setVisible(true);
        reservaServicio.setVisible(false);
        reservaGuia.setVisible(false);
        reservaRecurso.setVisible(false);
        reservaRut.setVisible(false);
    }//GEN-LAST:event_btnReservaGuardarActionPerformed

    private void btnReservaAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservaAgregarActionPerformed
        String rut = txtReservaCodigo.getText().trim();
        if (util.Validador.rutValido(rut)) {
            listaTemporalRuts.add(rut);
            javax.swing.JOptionPane.showMessageDialog(this, "Cliente agregado: " + rut);
            txtReservaCodigo.setText("");
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "RUT inválido.");
        }
    }//GEN-LAST:event_btnReservaAgregarActionPerformed

    private void btnRerservaCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRerservaCancelarActionPerformed

        listaTemporalRuts.clear();

        cmbReservaServicio.setSelectedIndex(0);
        cmbReservaGuia.setSelectedIndex(0);
        cmbReservaRecurso.setSelectedIndex(0);
        txtReservaCodigo.setText("");

        txtReservaCodigo.setVisible(false);
        btnReservaAgregar.setVisible(false);
        cmbReservaServicio.setVisible(false);
        cmbReservaGuia.setVisible(false);
        cmbReservaRecurso.setVisible(false);
        btnReservaGuardar.setVisible(false);
        btnRerservaCancelar.setVisible(false);
        reservaServicio.setVisible(false);
        reservaGuia.setVisible(false);
        reservaRecurso.setVisible(false);
        reservaRut.setVisible(false);

        javax.swing.JOptionPane.showMessageDialog(this, "Reserva cancelada. Los datos han sido borrados.");
    }//GEN-LAST:event_btnRerservaCancelarActionPerformed

    private void btnReservaVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservaVerActionPerformed
        String informe = gres.generarInforme(gp, gr, gs);
        txtaPanelBlanco.setText(informe);
    }//GEN-LAST:event_btnReservaVerActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        int opcion = javax.swing.JOptionPane.showConfirmDialog(
                this,
                "¿Está seguro de que desea salir de la aplicación?",
                "Confirmar Salida",
                javax.swing.JOptionPane.YES_NO_OPTION
        );

        if (opcion == javax.swing.JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnReservaEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservaEliminarActionPerformed
        String codigo = txtReservaEliminar.getText();

        boolean eliminado = gres.eliminarReservaPorCodigo(codigo);

        if (eliminado) {
            motor.guardarReservas(gres.getListaReservas());
            JOptionPane.showMessageDialog(null, "Reserva eliminada exitosamente.");
        } else {
            JOptionPane.showMessageDialog(null, "No se encontró una reserva con ese código.");
        }
    }//GEN-LAST:event_btnReservaEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrarPersona;
    private javax.swing.JButton btnBorrarRecurso;
    private javax.swing.JButton btnBorrarServicio;
    private javax.swing.JButton btnRegistrarPersona;
    private javax.swing.JButton btnRegistrarRecurso;
    private javax.swing.JButton btnRegistrarServicio;
    private javax.swing.JButton btnRerservaCancelar;
    private javax.swing.JButton btnReservaAgregar;
    private javax.swing.JButton btnReservaEliminar;
    private javax.swing.JButton btnReservaGuardar;
    private javax.swing.JButton btnReservaVer;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnVerPersona;
    private javax.swing.JButton btnVerRecurso;
    private javax.swing.JButton btnVerServicio;
    private javax.swing.JComboBox<String> cmbDisponible;
    private javax.swing.JComboBox<String> cmbPersonas;
    private javax.swing.JComboBox<String> cmbRecursos;
    private javax.swing.JComboBox<String> cmbReservaGuia;
    private javax.swing.JComboBox<String> cmbReservaMes;
    private javax.swing.JComboBox<String> cmbReservaRecurso;
    private javax.swing.JComboBox<String> cmbReservaServicio;
    private javax.swing.JComboBox<String> cmbServicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JLabel personaNombre;
    private javax.swing.JLabel personaRut;
    private javax.swing.JLabel personaTelefono;
    private javax.swing.JLabel personaVariable;
    private javax.swing.JLabel recursoCodigo;
    private javax.swing.JLabel recursoDisponible;
    private javax.swing.JLabel recursoNombre;
    private javax.swing.JLabel recursoTexto;
    private javax.swing.JLabel recursoTexto2;
    private javax.swing.JLabel recursoVariable;
    private javax.swing.JLabel reservaCodigo;
    private javax.swing.JLabel reservaGuia;
    private javax.swing.JLabel reservaRecurso;
    private javax.swing.JLabel reservaRut;
    private javax.swing.JLabel reservaServicio;
    private javax.swing.JLabel reservaTexto;
    private javax.swing.JLabel reservaTexto2;
    private javax.swing.JLabel servicioCantidad;
    private javax.swing.JLabel servicioCodigo;
    private javax.swing.JLabel servicioNombre;
    private javax.swing.JLabel servicioTexto;
    private javax.swing.JLabel servicioTexto2;
    private javax.swing.JLabel servicioVariable;
    private javax.swing.JPanel tabPersonas;
    private javax.swing.JTabbedPane tabPricipal;
    private javax.swing.JPanel tabRecursos;
    private javax.swing.JPanel tabReservas;
    private javax.swing.JPanel tabServicios;
    private javax.swing.JTextField txtPersonaNombre;
    private javax.swing.JTextField txtPersonaRut;
    private javax.swing.JTextField txtPersonaTelefono;
    private javax.swing.JTextField txtPersonaVariable;
    private javax.swing.JTextField txtRecursoCodigo;
    private javax.swing.JTextField txtRecursoNombre;
    private javax.swing.JTextField txtRecursoVariable;
    private javax.swing.JTextField txtReservaCodigo;
    private javax.swing.JTextField txtReservaEliminar;
    private javax.swing.JTextField txtServicioCantidad;
    private javax.swing.JTextField txtServicioCodigo;
    private javax.swing.JTextField txtServicioNombre;
    private javax.swing.JTextField txtServicioVariable;
    private javax.swing.JTextArea txtaPanelBlanco;
    // End of variables declaration//GEN-END:variables
}
